### PR TITLE
T0280 Muskathlon Company Donation form

### PR DESCRIPTION
**Pull request by clementcharmillot**
Adds a new `Company` field for the form. The value is saved in `res_partner.company_name`.

image

## Task
Can we adapte the donation form for companies? 
Can we have a drop down menu to chose name or company?
We have quite a few companies donating, so it would be nice to give the opinion to chose whether it is a company or person who donates.

### CODE REVIEW

**Review by NoeBerdoz — CHANGES_REQUESTED** [review]
To no create a potential case of redundant field, the "Company" field you implemented shouldn't be shown if the form is in b2b mode, see reference here: [templates.xm in odoo website_sale module](https://github.com/odoo/odoo/blob/f2765d2cab5671a010404c36842bf1b4c4d6350b/addons/website_sale/views/templates.xml#L1457)

**Comment by NoeBerdoz** [comment]
The translations of the new implemented field are missing, please add the french and german translations

**Comment by clementcharmillot** [comment]
There exists a template in Odoo to show the company and VAT 

image

named `website_sale.address_b2b`, defined in file `addons/website_sale/views/templates.xml:1457`.
The view is disabled in the database on the Muskathlon website, and can be activated in the `views` settings.

The status of the view can also be found by running the following SQL query:
```sql
select w.name, iuv.key, iuv.active, iuv.customize_show , * from ir_ui_view iuv
left join website w on w.id = iuv.website_id
where iuv."key" = 'website_sale.address_b2b' and w.name like 'Muskathlon';
```

Should we enable this view instead of adding it manually?

**Comment by ecino** [comment]
Yes it would be better. However we don't wan't the `VAT` field. So maybe you could inherit this `b2b` template only to hide the VAT field and then we can activate it in production.

**Review by ecino — APPROVED** [review]

**Pull request merged**
